name: Run ENTSO-E pipeline scripts        # shows in Actions tab

on:
  push:                                   # every commit / PR
  schedule:
    - cron:  '0 3 * * 1'                  # Monday 03:00 UTC

env:                                      
  ENTSOE_PAT: ${{ secrets.ENTSOE_PAT }}

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          install.packages(c(
            "entsoeapi","openxlsx","dplyr","tidyr","lubridate"
          ))

      - name: Execute scripts (5-min cap each)
        run: |
          timeout 300 Rscript scripts/entsoe_capacity.R
          timeout 300 Rscript scripts/entsoe_load.R
          timeout 300 Rscript scripts/entsoe_generation.R
          timeout 300 Rscript scripts/summary_generation.R
