name: ENTSO-E Data Downloader
on:
  push:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:

env:
  ENTSOE_PAT: ${{ secrets.ENTSOE_PAT }}
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev

      - name: Install entsoeapi & dependencies
        run: |
          Rscript -e "install.packages(
                        c('openxlsx', 'dplyr', 'tidyr', 'lubridate',
                          'readxl', 'tibble', 'writexl', 'remotes',
                          'httr', 'xmlconvert', 'curl'),
                        repos = 'https://cloud.r-project.org'
                      )"
          Rscript -e "remotes::install_github(
                        'krose/entsoeapi',
                        ref = 'master',
                        dependencies = FALSE
                      )"
          Rscript -e "library(entsoeapi); message('entsoeapi version: ', packageVersion('entsoeapi'))"

      - name: Execute pipeline scripts
        run: |
          timeout 300 Rscript scripts/entsoe_capacity.R
          timeout 300 Rscript scripts/entsoe_load.R
          timeout 300 Rscript scripts/entsoe_generation.R
          timeout 300 Rscript scripts/summary_generation.R
